// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfvc0TNZTc9OPY4mlvCHizuInxvpjnSNQ',
    appId: '1:217472044050:web:7825bbe2eed86ff3445ccb',
    messagingSenderId: '217472044050',
    projectId: 'iman-plus',
    authDomain: 'iman-plus.firebaseapp.com',
    storageBucket: 'iman-plus.appspot.com',
    measurementId: 'G-ERD25SW2FM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA181cqAAhT4m-QfRJgc7dcoaXkDBmOEIA',
    appId: '1:217472044050:android:a7b7408b0613a333445ccb',
    messagingSenderId: '217472044050',
    projectId: 'iman-plus',
    storageBucket: 'iman-plus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMr9EnDpmBWQI1F237lg0lM9pdNRIa8yU',
    appId: '1:217472044050:ios:b54579c51ef62365445ccb',
    messagingSenderId: '217472044050',
    projectId: 'iman-plus',
    storageBucket: 'iman-plus.appspot.com',
    iosBundleId: 'com.example.imanPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMr9EnDpmBWQI1F237lg0lM9pdNRIa8yU',
    appId: '1:217472044050:ios:b54579c51ef62365445ccb',
    messagingSenderId: '217472044050',
    projectId: 'iman-plus',
    storageBucket: 'iman-plus.appspot.com',
    iosBundleId: 'com.example.imanPlus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfvc0TNZTc9OPY4mlvCHizuInxvpjnSNQ',
    appId: '1:217472044050:web:a58fd410d2259bd9445ccb',
    messagingSenderId: '217472044050',
    projectId: 'iman-plus',
    authDomain: 'iman-plus.firebaseapp.com',
    storageBucket: 'iman-plus.appspot.com',
    measurementId: 'G-N0GLX3WXJ8',
  );
}
